# Generated by Django 5.2.3 on 2025-10-24 04:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField(verbose_name='شماره آیه')),
                ('page_number', models.IntegerField(verbose_name='شماره صفحه')),
                ('section_number', models.IntegerField(verbose_name='شماره حزب')),
                ('juz', models.IntegerField(verbose_name='جزء')),
            ],
            options={
                'verbose_name': 'آیه',
                'verbose_name_plural': 'آیات',
            },
        ),
        migrations.CreateModel(
            name='Qari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قاری')),
                ('path', models.CharField(max_length=200, verbose_name='مسیر فایل')),
                ('link', models.URLField(verbose_name='لینک فایل')),
                ('type', models.CharField(choices=[('tartil', 'ترتیل'), ('tajvid', 'تجوید'), ('tahdir', 'تحدیر'), ('tutorial', 'آموزشی'), ('translation', 'ترجمه'), ('word', 'کلمه'), ('intersection', 'تقطیع'), ('wordAudio', 'صوت کلمه')], max_length=100, verbose_name='نوع قاری')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='زبان')),
                ('narrator', models.CharField(max_length=100, verbose_name='راوی')),
            ],
            options={
                'verbose_name': 'قاری',
                'verbose_name_plural': 'قاری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_code', models.CharField(max_length=50, verbose_name='کد ریشه')),
                ('root_arabic', models.CharField(max_length=50, verbose_name='ریشه عربی')),
                ('root_english', models.CharField(max_length=100, verbose_name='ریشه انگلیسی')),
                ('meanings', models.TextField(blank=True, null=True, verbose_name='معانی')),
                ('newroot', models.CharField(blank=True, max_length=50, null=True, verbose_name='ریشه جدید')),
            ],
            options={
                'verbose_name': 'ریشه',
                'verbose_name_plural': 'ریشه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سوره')),
                ('arabic_name', models.CharField(max_length=100, verbose_name='نام عربی سوره')),
                ('english_name', models.CharField(max_length=100, verbose_name='نام انگلیسی سوره')),
                ('english_meaning', models.CharField(max_length=100, verbose_name='معنای انگلیسی سوره')),
            ],
            options={
                'verbose_name': 'سوره',
                'verbose_name_plural': 'سوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مترجم / منبع')),
                ('language', models.CharField(default='fa', max_length=20, verbose_name='زبان')),
                ('translation_type', models.CharField(choices=[('verse', 'ترجمه آیه'), ('word', 'ترجمه کلمه\u200cای'), ('tafseer', 'تفسیر'), ('audio', 'فایل صوتی')], default='verse', max_length=20, verbose_name='نوع ترجمه')),
            ],
            options={
                'verbose_name': 'مترجم / منبع',
                'verbose_name_plural': 'مترجمان / منابع',
            },
        ),
        migrations.CreateModel(
            name='UnwantedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='کلمه بی\u200cاهمیت')),
            ],
            options={
                'verbose_name': 'کلمه بی\u200cاهمیت',
                'verbose_name_plural': 'کلمات بی\u200cاهمیت',
            },
        ),
        migrations.CreateModel(
            name='VerseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain', models.TextField(verbose_name='متن بدون اعراب')),
                ('semi_tashkeel', models.TextField(verbose_name='متن نیم\u200cاعراب\u200cگذاری')),
                ('simple_tashkeel', models.TextField(verbose_name='متن اعراب\u200cگذاری ساده')),
                ('full_tashkeel', models.TextField(verbose_name='متن اعراب\u200cگذاری کامل')),
                ('persian_friendly', models.TextField(verbose_name='متن برای جستجو فارسی')),
                ('fuzzy', models.TextField(verbose_name='جستجوی فازی')),
            ],
            options={
                'verbose_name': 'متن آیه',
                'verbose_name_plural': 'متون آیات',
            },
        ),
        migrations.CreateModel(
            name='WordSearchTableMV',
            fields=[
                ('verse', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='quran.verse')),
                ('verse_number', models.SmallIntegerField()),
                ('first_word', models.TextField(null=True)),
                ('first_word_clean', models.TextField(null=True)),
                ('second_word_clean', models.TextField(null=True)),
                ('third_word_clean', models.TextField(null=True)),
                ('last_word', models.TextField(null=True)),
                ('last_word_clean', models.TextField(null=True)),
                ('second_last_word_clean', models.TextField(null=True)),
                ('third_last_word_clean', models.TextField(null=True)),
            ],
            options={
                'db_table': 'search_table',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='verse',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verses', to='quran.surah', verbose_name='سوره'),
        ),
        migrations.CreateModel(
            name='TranslationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField(verbose_name='شناسه صوت')),
                ('from_aya', models.IntegerField(verbose_name='از آیه')),
                ('to_aya', models.IntegerField(verbose_name='تا آیه')),
                ('first_type', models.CharField(max_length=125, verbose_name='اطلاعات صوت')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.surah', verbose_name='سوره')),
                ('translator', models.ForeignKey(limit_choices_to={'translation_type': 'audio'}, on_delete=django.db.models.deletion.PROTECT, related_name='translation_audio', to='quran.translator', verbose_name='منبع صوتی')),
            ],
            options={
                'verbose_name': 'فایل صوتی ترجمه',
                'verbose_name_plural': 'فایل\u200cهای صوتی ترجمه',
            },
        ),
        migrations.CreateModel(
            name='TafseerAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField(verbose_name='شناسه صوت')),
                ('from_aya', models.IntegerField(verbose_name='از آیه')),
                ('to_aya', models.IntegerField(verbose_name='تا آیه')),
                ('audio_link', models.CharField(max_length=50, verbose_name='لینک صوتی تفسیر')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.surah', verbose_name='سوره')),
                ('translator', models.ForeignKey(limit_choices_to={'translation_type': 'audioTafseer'}, on_delete=django.db.models.deletion.PROTECT, related_name='tafseer_audio', to='quran.translator', verbose_name='منبع تفسیر صوتی')),
            ],
            options={
                'verbose_name': 'فایل صوتی تفسیر',
                'verbose_name_plural': 'فایل\u200cهای صوتی تفسیر',
            },
        ),
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_aya', models.IntegerField(verbose_name='از آیه')),
                ('to_aya', models.IntegerField(verbose_name='تا آیه')),
                ('text', models.TextField(verbose_name='متن تفسیر')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.surah', verbose_name='سوره')),
                ('translator', models.ForeignKey(limit_choices_to={'translation_type': 'tafseer'}, on_delete=django.db.models.deletion.PROTECT, related_name='tafseer', to='quran.translator', verbose_name='منبع تفسیر')),
            ],
            options={
                'verbose_name': 'تفسیر',
                'verbose_name_plural': 'تفاسیر',
            },
        ),
        migrations.CreateModel(
            name='VerseRootIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.IntegerField(verbose_name='تطابق')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.root', verbose_name='ریشه')),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.verse', verbose_name='آیه')),
            ],
            options={
                'verbose_name': 'شاخص ریشه آیه',
                'verbose_name_plural': 'شاخص\u200cهای ریشه آیه',
            },
        ),
        migrations.AddField(
            model_name='verse',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quran.versetext', verbose_name='متن آیه'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_text', models.TextField(verbose_name='متن عربی')),
                ('persian_text', models.TextField(blank=True, null=True, verbose_name='ترجمه فارسی')),
                ('english_text', models.TextField(blank=True, null=True, verbose_name='ترجمه انگلیسی')),
                ('word_number', models.IntegerField(blank=True, null=True, verbose_name='شماره کلمه')),
                ('verse_number', models.IntegerField(blank=True, null=True, verbose_name='شماره آیه')),
                ('type', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='نوع کلمه')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='شماره خط')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='شماره صفحه')),
                ('code_ski_word', models.IntegerField(blank=True, null=True, verbose_name='کد SKI')),
                ('aya_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wordsi', to='quran.verse', verbose_name='ایندکس ایه')),
                ('qari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quran.qari')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='quran.surah', verbose_name='سوره')),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='quran.verse', verbose_name='آیه')),
            ],
            options={
                'verbose_name': 'کلمه',
                'verbose_name_plural': 'کلمات',
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meanings', models.JSONField(blank=True, null=True, verbose_name='ترجمه مخصوص')),
                ('root_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه ریشه')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.surah', verbose_name='سوره')),
                ('translator', models.ForeignKey(limit_choices_to={'translation_type': 'word'}, on_delete=django.db.models.deletion.PROTECT, related_name='word_meaning', to='quran.translator', verbose_name='منبع')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_meanings', to='quran.verse', verbose_name='آیه')),
            ],
            options={
                'verbose_name': 'ترجمه کلمه\u200cای',
                'verbose_name_plural': 'ترجمه\u200cهای کلمه\u200cای',
            },
        ),
        migrations.CreateModel(
            name='SearchTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verse_number', models.IntegerField()),
                ('PageNum', models.PositiveIntegerField(db_index=True, verbose_name='شماره صفحه')),
                ('JozNum', models.PositiveIntegerField(db_index=True, verbose_name='شماره جزء')),
                ('HezbNum', models.PositiveIntegerField(db_index=True, verbose_name='شماره حزب')),
                ('positioninpage', models.PositiveIntegerField(db_index=True, verbose_name='مکان در صفحه')),
                ('SearchSP', models.TextField(blank=True, null=True, verbose_name='SearchSP')),
                ('SearchP', models.TextField(blank=True, null=True, verbose_name='SearchP')),
                ('SearchAE', models.TextField(blank=True, null=True, verbose_name='SearchAE')),
                ('SearchSA', models.TextField(blank=True, null=True, verbose_name='SearchSA')),
                ('SearchA', models.TextField(blank=True, null=True, verbose_name='SearchA')),
                ('SearchAE2', models.TextField(blank=True, null=True, verbose_name='SearchAE2')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_verse', to='quran.verse', verbose_name='آیه')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_surah', to='quran.surah', verbose_name='سوره')),
            ],
            options={
                'verbose_name': 'Search Table',
                'verbose_name_plural': 'Search Tables',
                'ordering': ['surah', 'verse', 'PageNum', 'positioninpage'],
                'indexes': [models.Index(fields=['surah', 'verse'], name='quran_searc_surah_i_07ec8b_idx'), models.Index(fields=['PageNum'], name='quran_searc_PageNum_4ffda0_idx'), models.Index(fields=['JozNum'], name='quran_searc_JozNum_6465ef_idx'), models.Index(fields=['HezbNum'], name='quran_searc_HezbNum_685a3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن ترجمه')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='quran.surah', verbose_name='سوره')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verse_translations', to='quran.translator', verbose_name='مترجم / منبع')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='quran.verse', verbose_name='آیه')),
            ],
            options={
                'verbose_name': 'ترجمه آیه',
                'verbose_name_plural': 'ترجمه\u200cهای آیات',
                'unique_together': {('surah', 'translator', 'verse')},
            },
        ),
    ]
