# Generated by Django 5.2.3 on 2025-10-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnwantedWord',
        ),
    ]
